### ISSUE TITLE
Keeping up with releases

### ISSUE THREAD

**Issue by WaitlistedJay** [FEStoRB/FNFestivaltoRB#1]
Not really an issue, but is there a way to keep up with new full conversions? Perhaps a Discord server or anything else

**Comment by FEStoRB** [comment]
The less eyes on this the better, for legal reasons. 

There are a couple of discords that have a Github tracker tracking this repo. 
I'd recommend the RB MCP or Rock Band Road Crew.

https://discord.com/invite/gbvaKrrvyV
