### ISSUE TITLE
Error in: Master of Puppets (separate word)

### ISSUE THREAD

**Issue by Alanzinho720** [FEStoRB/FNFestivaltoRB#15]
![Screenshot_20241025-210501~2](https://github.com/user-attachments/assets/7434ba3a-f884-4e62-8746-2c9e9c5a5136)

**Comment by C0Assassin** [comment]
Can you post a screenshot of the error in RB1 2 3 4 or Lego please? Thanks

**Comment by Alanzinho720** [comment]
![InShot_20241026_013239343](https://github.com/user-attachments/assets/fcda482a-cd6e-4b99-b91e-41d4cd745faa)

**Comment by Alanzinho720** [comment]
![InShot_20241026_013239343](https://github.com/user-attachments/assets/fcda482a-cd6e-4b99-b91e-41d4cd745faa)

**Comment by FEStoRB** [comment]
https://github.com/FEStoRB/FNFestivaltoRB/commit/76f58bbe49c91fc35dd087c185fe46eebd8949df

Fixed with latest commit
