### ISSUE TITLE
Killing In The Name vocal audio track as Guitar audio track

### ISSUE THREAD

**Issue by stuffnthingzz** [FEStoRB/FNFestivaltoRB#20]
https://github.com/user-attachments/assets/7d843d89-e4e7-421c-a972-cc4e2a6459c3

When guitar track cuts out, vocals audio cuts out instead
[edit: H625 video does not play in firefox for some reason, but it plays in chromium]

**Comment by FEStoRB** [comment]
I believe I may have fixed the issue in the latest commit: https://github.com/FEStoRB/FNFestivaltoRB/commit/77f4a0ba8ed3eb75ea3300334844786b1050dc92

I'm unsure whether its truly fixed or not as I have no method to test the song atm, so a follow up from you on this will be appreciated.

**Comment by stuffnthingzz** [comment]
It is fixed now, and the guitar properly mutes and has whammy
