### ISSUE TITLE
What defines basic/full conversion?

### ISSUE THREAD

**Issue by Sebuza** [FEStoRB/FNFestivaltoRB#9]
I've been using these conversions haven't looked deeply into the files. What does it mean for a conversion to be full?

**Comment by FEStoRB** [comment]
a full conversion is a human authored venue with human authored lipsync and a playable vocals charts.
basic conversions are auto generated via passing through magma, with no playable vocals chart, randomized lipsync, and the bare minimum venue venue animations.

**Comment by appsforartists** [comment]
Does this mean that all songs in this repo have their instrument tracks source-to-source converted from the Festival format to the Rock Band format, and "full" conversions also have manual recreations of the vocals?

I'm trying to understand if these are essentially the same MIDI tracks in a different format, or if they're recreations.

**Comment by C0Assassin** [comment]
> I'm trying to understand if these are essentially the same MIDI tracks in a different format, or if they're recreations.

All songs use the real midis. Whether theyre basic or full. Basic is just an automated process with hardly any human input or work put into it, its fed into a program to get the raw Fes midi playable in Rock Band at its bare minimum. What you see is what you get.

A full conversion is, again, the midi from Fes, manually converted to work in Rock Band. Which means, it has playable vocal charts, a proper venue track, and human authored lipsyncing. The quality of these are more akin to an actual HMX dlc release.
